# This file specifies your Python application's runtime configuration
# including URL routing, versions, static file uploads, etc. See
# https://developers.google.com/appengine/docs/python/config/appconfig
# for details.

# TODO: Enter your application id below. If you have signed up
# using cloud.google.com/console use the "project id" for your application
# id.
application: PROJECT_ID
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: 0s

# Handlers define how to route requests to your application.

# urllib3.contrib.appengine module for error: AppEnginePlatformWarning: urllib3 is using URLFetch on Google App Engine sandbox instead of sockets
#env_variables:
#    GAE_USE_SOCKETS_HTTPLIB : 'true'

instance_class: F1
automatic_scaling:
  max_idle_instances: automatic  # default value
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  #max_concurrent_requests: 50
  #min_idle_instances: 5

#inbound_services:
#- warmup

libraries:
- name: jinja2
  version: latest

handlers:
- url: /favicon.ico
  static_files: main/static/
  upload: main/static/favicon.ico

- url: /bower_components
  static_dir: main/static/bower_components

- url: /node_modules
  static_dir: main/static/node_modules

- url: /app
  static_dir: main/React/dist
  mime_type: text/javascript

- url: /js
  static_dir: main/static/js
  mime_type: text/javascript

- url: /img
  static_dir: main/static/img

- url: /css
  static_dir: main/static/css
  mime_type: text/css

- url: /language
  static_dir: static/language

- url: /fonts
  static_dir: main/static/fonts
  expiration: "0d 10m"

- url: /.*
  script: main.app
  secure: always

skip_files:
- ^\.idea$
- ^\.git$
- ^.*.swp$
- ^.*.swo$
- ^.DS_Store$
- ^\.appcfg_oauth2_tokens$
- ^dev_tools$
- lib/setuptools/script\ \(dev\).tmpl
- ^tmp$
- ^.bowerc$
- ^bower.json$
- ^package.json$
- ^run.py$
- ^requirements.txt$
- ^README.md$
- ^yarn.lock$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*\.md$
- ^(.*/)?\..*$
